# Definimod el tipo de base de datos
quarkus.datasource.db-kind=postgresql
## Usuario con el que se conecta a la base de datos
quarkus.datasource.username=postgres
quarkus.datasource.password=2901
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5433/pa2DB3
## Sincroización de la base de datos con el codigo
quarkus.hibernate-orm.database.generation=update
## Mostrar las consultas SQL en la consola
quarkus.hibernate-orm.log.sql=true